// AUTO-GENERATED by scripts/gen-top-lineups-data.mjs
// Do not edit manually — re-run the script to regenerate

export type TopLineup = { ids: number[]; names: string[]; active: boolean[]; count: number; seasons: number[] };
export type TopTeamData = { name: string; totalNights: number; uniqueLineups: number; lineups: TopLineup[] };

export const ALL_TOP_LINEUPS: TopTeamData[] = [
  {
    name: "Alley Oops",
    totalNights: 289,
    uniqueLineups: 136,
    lineups: [
      { ids: [64,152,582,620], names: ["Bob Wall","Dave Bjorkback","Stephen Conrad","Viva Massung"], active: [false,true,true,false], count: 17, seasons: [4,5,6,7,10,11,14] },
      { ids: [152,155,582,620], names: ["Dave Bjorkback","Dave Heller","Stephen Conrad","Viva Massung"], active: [true,false,true,false], count: 14, seasons: [2,3] },
      { ids: [152,372,582,620], names: ["Dave Bjorkback","Kelly Davis","Stephen Conrad","Viva Massung"], active: [true,false,true,false], count: 13, seasons: [8,9,10,11,12] },
    ],
  },
  {
    name: "Bowl Durham",
    totalNights: 61,
    uniqueLineups: 30,
    lineups: [
      { ids: [33,419,528,618], names: ["Anna Celander","Madelyne Rush","Rebecca Pattillo","Vance Woods"], active: [true,true,true,true], count: 9, seasons: [29,31,32] },
      { ids: [33,107,419,528], names: ["Anna Celander","Charlotte Asmuth","Madelyne Rush","Rebecca Pattillo"], active: [true,true,true,true], count: 8, seasons: [29,30] },
      { ids: [33,266,419,528], names: ["Anna Celander","Jacob Steagald","Madelyne Rush","Rebecca Pattillo"], active: [true,true,true,true], count: 6, seasons: [33,34] },
    ],
  },
  {
    name: "E-Bowla",
    totalNights: 308,
    uniqueLineups: 30,
    lineups: [
      { ids: [24,271,575,615], names: ["Amy Kostrewa","James Hepler","Spott Philpott","Tracy Wills"], active: [true,true,true,true], count: 207, seasons: [5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25,26,27,28,29,30,31,32,33,34,35] },
      { ids: [24,575,604,615], names: ["Amy Kostrewa","Spott Philpott","Tim Ross","Tracy Wills"], active: [true,true,false,true], count: 31, seasons: [2,3,4,7,8,9,10,12] },
      { ids: [24,135,575,615], names: ["Amy Kostrewa","Cy Rawls","Spott Philpott","Tracy Wills"], active: [true,false,true,true], count: 17, seasons: [1,2] },
    ],
  },
  {
    name: "Fancy Pants",
    totalNights: 303,
    uniqueLineups: 145,
    lineups: [
      { ids: [113,115,247,534], names: ["Chris Gilchrist","Chris Rossi","Holly Leddy","Richard Hair"], active: [false,false,false,false], count: 32, seasons: [1,2,3,4,6,7] },
      { ids: [111,215,268,471], names: ["Chris Chapman","Fikri Yucel","Jaimie Lea","Michael Daul"], active: [true,true,true,true], count: 18, seasons: [22,23,24,25,26,28,29,31,32,34] },
      { ids: [113,115,215,247], names: ["Chris Gilchrist","Chris Rossi","Fikri Yucel","Holly Leddy"], active: [false,false,true,false], count: 9, seasons: [6,7,9,12,13] },
    ],
  },
  {
    name: "Grandma's Teeth",
    totalNights: 51,
    uniqueLineups: 14,
    lineups: [
      { ids: [63,312,479,540], names: ["Bob Ellinger","Joe Brogan","Mike DePasquale","Robyn Livingston"], active: [true,true,true,true], count: 25, seasons: [30,31,32,33,34] },
      { ids: [63,172,312,479], names: ["Bob Ellinger","Derek Sanger","Joe Brogan","Mike DePasquale"], active: [true,true,true,true], count: 6, seasons: [33,35] },
      { ids: [63,234,312,479], names: ["Bob Ellinger","Hani Elwafi","Joe Brogan","Mike DePasquale"], active: [true,true,true,true], count: 4, seasons: [30,33,35] },
    ],
  },
  {
    name: "Gutterglory",
    totalNights: 307,
    uniqueLineups: 130,
    lineups: [
      { ids: [59,381,428,561], names: ["Bill Jenniches","Kevin Morgan","Mark Koyanagi","Scott Berrier"], active: [true,true,true,false], count: 44, seasons: [1,2,3,4,5,6,7,8,9,10,12,13,14,19,20] },
      { ids: [59,381,428,446], names: ["Bill Jenniches","Kevin Morgan","Mark Koyanagi","Matt Pittman"], active: [true,true,true,false], count: 15, seasons: [16,17,18,21,22,23,29] },
      { ids: [59,108,381,428], names: ["Bill Jenniches","Charlotte Walton","Kevin Morgan","Mark Koyanagi"], active: [true,false,true,true], count: 14, seasons: [1,2,4] },
    ],
  },
  {
    name: "Guttermouths",
    totalNights: 284,
    uniqueLineups: 121,
    lineups: [
      { ids: [15,84,324,470], names: ["Alix Bowman","Brooke Insley","John Terribili","Melissa Lee"], active: [true,true,true,true], count: 34, seasons: [29,30,31,32,33,34,35] },
      { ids: [15,142,224,347], names: ["Alix Bowman","Dan Nicholson","Genevieve d'Entremont","Kamal Bennoune"], active: [true,false,false,false], count: 12, seasons: [9,10,11,12] },
      { ids: [74,84,142,347], names: ["Brian Hawkins","Brooke Insley","Dan Nicholson","Kamal Bennoune"], active: [false,true,false,false], count: 12, seasons: [16,17,18,19,21] },
    ],
  },
  {
    name: "Guttersnipes",
    totalNights: 43,
    uniqueLineups: 24,
    lineups: [
      { ids: [5,134,416,610], names: ["Adam Hunter","Curtis Cushman","Lloyd Mason","Tom Page"], active: [true,true,true,true], count: 7, seasons: [31,32,33] },
      { ids: [5,134,416,568], names: ["Adam Hunter","Curtis Cushman","Lloyd Mason","Seth Horton"], active: [true,true,true,true], count: 5, seasons: [31,32] },
      { ids: [5,416,445,610], names: ["Adam Hunter","Lloyd Mason","Matt Northrup","Tom Page"], active: [true,true,true,true], count: 5, seasons: [34,35] },
    ],
  },
  {
    name: "HOT FUN",
    totalNights: 25,
    uniqueLineups: 10,
    lineups: [
      { ids: [168,318,455,618], names: ["Denis McPhillips","John Bellizzi","Matt Wade","Vance Woods"], active: [true,true,true,true], count: 10, seasons: [33,34,35] },
      { ids: [221,318,455,618], names: ["Freddy Giaever","John Bellizzi","Matt Wade","Vance Woods"], active: [true,true,true,true], count: 2, seasons: [33,34] },
      { ids: [168,221,318,455], names: ["Denis McPhillips","Freddy Giaever","John Bellizzi","Matt Wade"], active: [true,true,true,true], count: 2, seasons: [33,34] },
    ],
  },
  {
    name: "Hot Shotz",
    totalNights: 308,
    uniqueLineups: 77,
    lineups: [
      { ids: [154,293,295,512], names: ["Dave Graedon","Jennifer Hill","Jennifer Longee","Paul Marsh"], active: [true,false,false,true], count: 56, seasons: [4,5,6,7,10,11,13,14,15,16] },
      { ids: [154,200,295,512], names: ["Dave Graedon","Eric Roehrig","Jennifer Longee","Paul Marsh"], active: [true,false,false,true], count: 29, seasons: [1,2,3] },
      { ids: [154,374,512,597], names: ["Dave Graedon","Kelly Shirley","Paul Marsh","Ted Glick"], active: [true,true,true,true], count: 29, seasons: [24,27,28,29,30,31,32,33,34,35] },
    ],
  },
  {
    name: "Living on a Spare",
    totalNights: 16,
    uniqueLineups: 16,
    lineups: [
      { ids: [147,191,232,410], names: ["Danielle Gambogi","Ellen Duda","Griffin Hennelly","Lillith Fallon"], active: [true,true,true,true], count: 1, seasons: [34] },
      { ids: [191,296,410,488], names: ["Ellen Duda","Jenny Elander","Lillith Fallon","Natalie Pickett"], active: [true,true,true,true], count: 1, seasons: [34] },
      { ids: [147,186,191,583], names: ["Danielle Gambogi","Eliza Lawdley","Ellen Duda","Stephen Eren"], active: [true,true,true,true], count: 1, seasons: [34] },
    ],
  },
  {
    name: "Lucky Strikes",
    totalNights: 308,
    uniqueLineups: 124,
    lineups: [
      { ids: [326,391,483,548], names: ["John Williams","Kyle Hanlin","Mirla del Rosario","Russ Dean"], active: [true,false,false,true], count: 86, seasons: [1,2,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19] },
      { ids: [326,435,483,548], names: ["John Williams","Martin Hall","Mirla del Rosario","Russ Dean"], active: [true,true,false,true], count: 21, seasons: [14,15,16,17,20,21,22,24,25,26,27] },
      { ids: [121,225,435,548], names: ["Christina Manzella","Geoffrey Berry","Martin Hall","Russ Dean"], active: [true,true,true,true], count: 13, seasons: [32,33,34] },
    ],
  },
  {
    name: "Pin-Ups",
    totalNights: 308,
    uniqueLineups: 101,
    lineups: [
      { ids: [122,559,578,608], names: ["Christina Pelech","Sarah Martin","Stacie Smith","Tino McCullough"], active: [true,true,false,true], count: 36, seasons: [3,4,5,6,7,8,11,12,13] },
      { ids: [46,61,218,608], names: ["Barrett Jorgensen","Blake Moriarty","Forrest DeMarcus","Tino McCullough"], active: [true,true,true,true], count: 22, seasons: [28,29,30,31,32,33,34,35] },
      { ids: [122,369,559,608], names: ["Christina Pelech","Kelley Shaw","Sarah Martin","Tino McCullough"], active: [true,false,true,true], count: 18, seasons: [8,9,10,11,12] },
    ],
  },
  {
    name: "Smoke-a-Bowl",
    totalNights: 140,
    uniqueLineups: 96,
    lineups: [
      { ids: [240,300,307,535], names: ["Hattie Pink","Jeremy Parker","Jillian Lea","Rob Mariani"], active: [false,false,true,false], count: 10, seasons: [18,19,20] },
      { ids: [7,194,317,409], names: ["Ady Pratapa","Emma Jane Richardson","John Bekas","Leslie Pierce"], active: [true,true,true,true], count: 7, seasons: [34,35] },
      { ids: [125,194,317,409], names: ["Clark Brunner","Emma Jane Richardson","John Bekas","Leslie Pierce"], active: [true,true,true,true], count: 5, seasons: [33] },
    ],
  },
  {
    name: "Sparadigm Shift",
    totalNights: 134,
    uniqueLineups: 54,
    lineups: [
      { ids: [89,291,299,474], names: ["Cameron Dye","Jennifer Dye","Jeremy Kumin","Michael Parks"], active: [true,true,true,true], count: 30, seasons: [28,29,30,31,32,33] },
      { ids: [14,133,299,603], names: ["Alison Trott","Crystal Lee","Jeremy Kumin","Tim Parrish"], active: [true,false,true,false], count: 16, seasons: [20,21,22,23] },
      { ids: [299,349,474,495], names: ["Jeremy Kumin","Karen Kumin","Michael Parks","Nicholas Burr"], active: [true,true,true,false], count: 9, seasons: [26,27] },
    ],
  },
  {
    name: "Stinky Cheese",
    totalNights: 169,
    uniqueLineups: 49,
    lineups: [
      { ids: [114,196,262,490], names: ["Chris Klindt","Enrico Boarati","Jack Driver","Nate Sisco"], active: [true,false,true,true], count: 17, seasons: [22,23,24,25,26,27] },
      { ids: [196,231,256,490], names: ["Enrico Boarati","Graham Killion","Isaac Coulbourne","Nate Sisco"], active: [false,false,false,true], count: 15, seasons: [16,17,19,20] },
      { ids: [114,262,490,585], names: ["Chris Klindt","Jack Driver","Nate Sisco","Steve Bishop"], active: [true,true,true,true], count: 14, seasons: [26,28,29,30,31,32] },
    ],
  },
  {
    name: "The Boom Kings",
    totalNights: 299,
    uniqueLineups: 64,
    lineups: [
      { ids: [238,388,563,611], names: ["Harper Gordek","Kristine Pryzgoda","Scott Jeffries","Tony Lawrence"], active: [true,true,true,true], count: 44, seasons: [11,13,15,16,17,18,19,20,21,22,23,24,25,26,27,28,29,30,32,33,34,35] },
      { ids: [65,388,563,611], names: ["Bobby Hundley","Kristine Pryzgoda","Scott Jeffries","Tony Lawrence"], active: [true,true,true,true], count: 33, seasons: [12,18,20,21,22,23,24,25,26,27,28,29,30,31,32,33,34,35] },
      { ids: [65,238,563,611], names: ["Bobby Hundley","Harper Gordek","Scott Jeffries","Tony Lawrence"], active: [true,true,true,true], count: 32, seasons: [12,13,16,20,21,22,23,24,25,26,28,29,30,31,32,33,34,35] },
    ],
  },
  {
    name: "Thoughts and Spares",
    totalNights: 239,
    uniqueLineups: 73,
    lineups: [
      { ids: [282,345,496,508], names: ["Jay Lowe","Justin Levens","Nick Cain","Patrick Nerz"], active: [false,false,false,false], count: 40, seasons: [9,10,11,12,13] },
      { ids: [11,202,387,496], names: ["Alex Rubenstein","Eric Thomas","Kristin Pearson","Nick Cain"], active: [true,true,true,false], count: 31, seasons: [18,19,20,21,22,23,24,25,26,27,28,29] },
      { ids: [11,202,496,508], names: ["Alex Rubenstein","Eric Thomas","Nick Cain","Patrick Nerz"], active: [true,true,false,false], count: 14, seasons: [16,18,19,20,21,22,24,25,27] },
    ],
  },
  {
    name: "Valley of the Balls",
    totalNights: 242,
    uniqueLineups: 106,
    lineups: [
      { ids: [90,297,306,330], names: ["Cameron Mitchell","Jenny Peters","Jessie Yonac","Jon Hunt"], active: [false,true,false,true], count: 17, seasons: [13,14,15,16] },
      { ids: [214,245,297,373], names: ["Farrell","Henry Hebert","Jenny Peters","Kelly Farrell"], active: [true,true,true,true], count: 11, seasons: [18,19,20,21,22,23] },
      { ids: [90,131,522,523], names: ["Cameron Mitchell","Courtney Mitchell","Rachel Canada","Rachel Ingold"], active: [false,false,false,false], count: 9, seasons: [8,9] },
    ],
  },
  {
    name: "Wild Llamas",
    totalNights: 238,
    uniqueLineups: 94,
    lineups: [
      { ids: [157,304,429,587], names: ["Dave Shaw","Jesse Troy","Mark Oates","Steve Stanczyk"], active: [true,true,true,true], count: 13, seasons: [18,19,20,21,24] },
      { ids: [157,211,370,429], names: ["Dave Shaw","Erin Kauffman","Kellie Gates","Mark Oates"], active: [true,false,false,true], count: 10, seasons: [12,13,14] },
      { ids: [157,429,529,587], names: ["Dave Shaw","Mark Oates","Rebecca Shaw","Steve Stanczyk"], active: [true,true,false,true], count: 10, seasons: [22,23,25] },
    ],
  },
];
